// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8wWg1M27IxwWoUJ_gouODHJEgJ7IRoec',
    appId: '1:84273076690:web:1691f461f9b06a77c1100b',
    messagingSenderId: '84273076690',
    projectId: 'indclassifieds-ac8a0',
    authDomain: 'indclassifieds-ac8a0.firebaseapp.com',
    storageBucket: 'indclassifieds-ac8a0.firebasestorage.app',
    measurementId: 'G-MLLNXQWK7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWGfhFYpm5UaI2A8NOlMsXBA3D8_3rNZc',
    appId: '1:84273076690:android:b4faee763d721695c1100b',
    messagingSenderId: '84273076690',
    projectId: 'indclassifieds-ac8a0',
    storageBucket: 'indclassifieds-ac8a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQy3oWXdN47-MRzcLxFepk-TSsGLYz7nM',
    appId: '1:84273076690:ios:bf69cd8ca2a4c684c1100b',
    messagingSenderId: '84273076690',
    projectId: 'indclassifieds-ac8a0',
    storageBucket: 'indclassifieds-ac8a0.firebasestorage.app',
    iosBundleId: 'com.ind.classifieds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQy3oWXdN47-MRzcLxFepk-TSsGLYz7nM',
    appId: '1:84273076690:ios:bf69cd8ca2a4c684c1100b',
    messagingSenderId: '84273076690',
    projectId: 'indclassifieds-ac8a0',
    storageBucket: 'indclassifieds-ac8a0.firebasestorage.app',
    iosBundleId: 'com.ind.classifieds',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8wWg1M27IxwWoUJ_gouODHJEgJ7IRoec',
    appId: '1:84273076690:web:7cd13788ad49da6dc1100b',
    messagingSenderId: '84273076690',
    projectId: 'indclassifieds-ac8a0',
    authDomain: 'indclassifieds-ac8a0.firebaseapp.com',
    storageBucket: 'indclassifieds-ac8a0.firebasestorage.app',
    measurementId: 'G-9QV59KY56E',
  );
}
